/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoanalizador.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import proyectoanalizador.backed.objetos.Lenguajes;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import proyectoanalizador.backed.objetos.InfLenguaje;

/**
 *
 * @author bryan
 */
public class DialogBorrarLenguaje extends javax.swing.JDialog {

    private Lenguajes seleccionado;
    private List<Lenguajes> listaLenguajes;
    private ObservableList<Lenguajes> listaObservable;

    
    /**
     * Creates new form DialogBorrarLenguaje
     */
    public DialogBorrarLenguaje(java.awt.Frame parent, boolean modal, List<Lenguajes> listaLenguajes) {
        super(parent, modal);
        this.listaLenguajes = listaLenguajes;
        this.listaObservable = ObservableCollections.observableList(new ArrayList<>());
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarTabla(listaLenguajes);
    }

    public ObservableList<Lenguajes> getListaObservable() {
        return listaObservable;
    }

    public void setListaObservable(ObservableList<Lenguajes> listaObservable) {
        this.listaObservable = listaObservable;
    }

    public Lenguajes getSeleccionado() {
        return seleccionado;
    }

    public void setSeleccionado(Lenguajes seleccionado) {
        this.seleccionado = seleccionado;
        if (this.seleccionado != null) {
            txtLenguajeSeleccionado.setText(this.seleccionado.getInformacionLenguaje().getNombre());
        }
    }

    public List<Lenguajes> getListaLenguajes() {
        return listaLenguajes;
    }

    public void setListaLenguajes(List<Lenguajes> listaLenguajes) {
        this.listaLenguajes = listaLenguajes;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblBorrarLenguaje = new javax.swing.JLabel();
        lblSeleccionado = new javax.swing.JLabel();
        txtLenguajeSeleccionado = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBorrarLenguaje.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBorrarLenguaje.setText("LENGUAJES:");

        lblSeleccionado.setText("Seleccionado:");

        txtLenguajeSeleccionado.setEditable(false);

        btnEliminar.setText("Borrar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaObservable}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${informacionLenguaje.nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${informacionLenguaje.autor}"));
        columnBinding.setColumnName("Autor");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${informacionLenguaje.extension}"));
        columnBinding.setColumnName("Extension");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${informacionLenguaje.lanzamiento}"));
        columnBinding.setColumnName("Lanzamiento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${informacionLenguaje.version}"));
        columnBinding.setColumnName("Version");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${seleccionado}"), jTable1, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBorrarLenguaje)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSeleccionado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLenguajeSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBorrarLenguaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccionado)
                    .addComponent(txtLenguajeSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (!txtLenguajeSeleccionado.getText().isEmpty()) {
            eliminarTabla(txtLenguajeSeleccionado.getText());
            JOptionPane.showMessageDialog(null, "Elimnado");
            txtLenguajeSeleccionado.setText("");
            actualizarTabla(listaLenguajes);
        } actualizarTabla(listaLenguajes);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void eliminarTabla(String eliminar){
        Lenguajes l = null;
        for (Lenguajes listaLenguaje : listaLenguajes) {
            if (listaLenguaje.getInformacionLenguaje().getNombre().equals(eliminar)) {
                l = listaLenguaje;
            }
        }
        if (l != null) {
            listaLenguajes.remove(l);
        }
        
        
    }
    
    private void actualizarTabla(List<Lenguajes> aux){
        this.listaObservable.clear();
        this.listaObservable.addAll(aux);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBorrarLenguaje;
    private javax.swing.JLabel lblSeleccionado;
    private javax.swing.JTextField txtLenguajeSeleccionado;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
