
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 02 01:36:02 CST 2020
//----------------------------------------------------

package proyectoanalizador.backed.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 33;
  public static final int CODIGO_FUENTE = 15;
  public static final int BARRA_VERTICAL = 30;
  public static final int INTERROGACION_C = 25;
  public static final int NOMBRE = 2;
  public static final int ENTERO = 9;
  public static final int DOS_PUNTOS = 31;
  public static final int LLAVE_C = 23;
  public static final int VERSION_NUMEROS = 36;
  public static final int LLAVE_A = 22;
  public static final int TABULADOR = 14;
  public static final int IDENTIFICADOR = 35;
  public static final int IGUAL = 17;
  public static final int VERSION = 3;
  public static final int MAYUSCULA = 34;
  public static final int ESPACIO_B = 13;
  public static final int LETRA_MAY = 39;
  public static final int AMPERSAND = 29;
  public static final int PUNTO_COMA = 18;
  public static final int EOF = 0;
  public static final int COMILLAS = 19;
  public static final int error = 1;
  public static final int COMA = 28;
  public static final int CADENA = 10;
  public static final int MENOS = 24;
  public static final int REAL = 11;
  public static final int PORCENTAJES = 16;
  public static final int NO = 8;
  public static final int AUTOR = 4;
  public static final int SIGNO = 40;
  public static final int PARENTESIS_C = 21;
  public static final int PARENTESIS_A = 20;
  public static final int REGLAS_SEMANTICAS = 32;
  public static final int EXTENSION = 5;
  public static final int SALTO_LINEA = 12;
  public static final int TERMINAL = 7;
  public static final int MINUSCULAS = 37;
  public static final int LANZAMIENTO = 6;
  public static final int LETRA_MIN = 38;
  public static final int MULTIPLICACION = 26;
  public static final int MAS = 27;
}

